network:
  default_ip: "127.0.0.1"
  default_port: 2905
  protocol: "SCTP"
logging:
  log_file: "logs/ss7_tool.log"
  log_level: "INFO"
ss7:
  api_key: test_key_123
  ssn: 6
  country_code: 91
  default_imsi: "123456789012345"
  default_msisdn: "9876543210"
  default_gt: "1234567890"
