# Logging configuration

version: 1
formatters:
  standard:
    format: "[%(asctime)s] %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/ss7_tool.log
    encoding: utf8
  
loggers:
  '':  # Root logger
    handlers: [console, file]
    level: DEBUG
    propagate: yes